#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: AIssays

# Short bio or description (displayed in the header)
description: Essays etc. on AI, academia, and all the world and his wife; by Thilo Stadelmann.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://stdm.github.io/images/stdm_small.jpg
favicon: https://stdm.github.io/images/favicon.png

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: stdm@zhaw.ch
  facebook:
  flickr:
  github: stdm
  instagram:
  linkedin: thilo-stadelmann
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: thilo_on_data
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: channel/UCqEjuibTwlVoO9bUW0oI0pA
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: aissays

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-122920628-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://stdm.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
#gems:
#  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
#  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

plugins:
  - jekyll-seo-tag

# Exclude these files from your production _site
exclude:
#  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

# show blog posts with dates in the future
future: true

#to allow UTF-8 encodings
encoding: utf-8

#generate excerpts automatically (added 2020-10-08)
page_excerpts: true